
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: elizabeth-stedi
spec:
  replicas: 1 #this is how many pods you will have
  selector:
    matchLabels:
      app: elizabeth-stedi
  template:
    metadata:
      labels:
        app: elizabeth-stedi
    spec:
      containers:
        - name: elizabeth-stedi
          image: "gcr.io/teca-350016/stedi-elizabeth:latest" 
          #you can get your project id in the google cloud
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3