
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: elizabeth-stedi
spec:
  replicas: 1 #this is how many pods you will have
  selector:
    matchLabels:
      app: elizabeth-stedi
  template:
    metadata:
      labels:
        app: elizabeth-stedi
    spec:
      containers:
        - name: elizabeth-stedi
          image: "gcr.io/teca-350016/stedi-elizabeth:latest" 
          #you can get your project id in the google cloud
          command: ["npm"]
          args: ["run","start"]
          ports:
            - containerPort: 433
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".1"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 443
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpsGet:
            # This is the url to call to see if my API has started
            path: /
            # Tjis is teh port to use to see if any of my API has started 
            port: 443
            # This is teh protocol to use to check if my API has started
            scheme: HTTPS
          initialDelaySeconds: 3
          periodSeconds: 3
--- #This three - separates two documents in a yaml file
#addding load balancers handles the web or user traffic to the K8s deployment
apiVersion: v1
kind: Service
metadata:
  name: elizabethstedi-loadbalancer
spec:
  selector:
    app: elizabeth-stedi
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
